// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire_format.proto

//package nearby.sharing.service.proto;

package sharing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sharingenums "kindshare/pb/sharingenums"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetadata_Type int32

const (
	FileMetadata_UNKNOWN      FileMetadata_Type = 0
	FileMetadata_IMAGE        FileMetadata_Type = 1
	FileMetadata_VIDEO        FileMetadata_Type = 2
	FileMetadata_ANDROID_APP  FileMetadata_Type = 3
	FileMetadata_AUDIO        FileMetadata_Type = 4
	FileMetadata_DOCUMENT     FileMetadata_Type = 5
	FileMetadata_CONTACT_CARD FileMetadata_Type = 6
)

// Enum value maps for FileMetadata_Type.
var (
	FileMetadata_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "IMAGE",
		2: "VIDEO",
		3: "ANDROID_APP",
		4: "AUDIO",
		5: "DOCUMENT",
		6: "CONTACT_CARD",
	}
	FileMetadata_Type_value = map[string]int32{
		"UNKNOWN":      0,
		"IMAGE":        1,
		"VIDEO":        2,
		"ANDROID_APP":  3,
		"AUDIO":        4,
		"DOCUMENT":     5,
		"CONTACT_CARD": 6,
	}
)

func (x FileMetadata_Type) Enum() *FileMetadata_Type {
	p := new(FileMetadata_Type)
	*p = x
	return p
}

func (x FileMetadata_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileMetadata_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[0].Descriptor()
}

func (FileMetadata_Type) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[0]
}

func (x FileMetadata_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FileMetadata_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FileMetadata_Type(num)
	return nil
}

// Deprecated: Use FileMetadata_Type.Descriptor instead.
func (FileMetadata_Type) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{0, 0}
}

type TextMetadata_Type int32

const (
	TextMetadata_UNKNOWN TextMetadata_Type = 0
	TextMetadata_TEXT    TextMetadata_Type = 1
	// Open with browsers.
	TextMetadata_URL TextMetadata_Type = 2
	// Open with map apps.
	TextMetadata_ADDRESS TextMetadata_Type = 3
	// Dial.
	TextMetadata_PHONE_NUMBER TextMetadata_Type = 4
)

// Enum value maps for TextMetadata_Type.
var (
	TextMetadata_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXT",
		2: "URL",
		3: "ADDRESS",
		4: "PHONE_NUMBER",
	}
	TextMetadata_Type_value = map[string]int32{
		"UNKNOWN":      0,
		"TEXT":         1,
		"URL":          2,
		"ADDRESS":      3,
		"PHONE_NUMBER": 4,
	}
)

func (x TextMetadata_Type) Enum() *TextMetadata_Type {
	p := new(TextMetadata_Type)
	*p = x
	return p
}

func (x TextMetadata_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextMetadata_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[1].Descriptor()
}

func (TextMetadata_Type) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[1]
}

func (x TextMetadata_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextMetadata_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextMetadata_Type(num)
	return nil
}

// Deprecated: Use TextMetadata_Type.Descriptor instead.
func (TextMetadata_Type) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{1, 0}
}

type WifiCredentialsMetadata_SecurityType int32

const (
	WifiCredentialsMetadata_UNKNOWN_SECURITY_TYPE WifiCredentialsMetadata_SecurityType = 0
	WifiCredentialsMetadata_OPEN                  WifiCredentialsMetadata_SecurityType = 1
	WifiCredentialsMetadata_WPA_PSK               WifiCredentialsMetadata_SecurityType = 2
	WifiCredentialsMetadata_WEP                   WifiCredentialsMetadata_SecurityType = 3
	WifiCredentialsMetadata_SAE                   WifiCredentialsMetadata_SecurityType = 4
)

// Enum value maps for WifiCredentialsMetadata_SecurityType.
var (
	WifiCredentialsMetadata_SecurityType_name = map[int32]string{
		0: "UNKNOWN_SECURITY_TYPE",
		1: "OPEN",
		2: "WPA_PSK",
		3: "WEP",
		4: "SAE",
	}
	WifiCredentialsMetadata_SecurityType_value = map[string]int32{
		"UNKNOWN_SECURITY_TYPE": 0,
		"OPEN":                  1,
		"WPA_PSK":               2,
		"WEP":                   3,
		"SAE":                   4,
	}
)

func (x WifiCredentialsMetadata_SecurityType) Enum() *WifiCredentialsMetadata_SecurityType {
	p := new(WifiCredentialsMetadata_SecurityType)
	*p = x
	return p
}

func (x WifiCredentialsMetadata_SecurityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiCredentialsMetadata_SecurityType) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[2].Descriptor()
}

func (WifiCredentialsMetadata_SecurityType) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[2]
}

func (x WifiCredentialsMetadata_SecurityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WifiCredentialsMetadata_SecurityType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WifiCredentialsMetadata_SecurityType(num)
	return nil
}

// Deprecated: Use WifiCredentialsMetadata_SecurityType.Descriptor instead.
func (WifiCredentialsMetadata_SecurityType) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{2, 0}
}

type Frame_Version int32

const (
	Frame_UNKNOWN_VERSION Frame_Version = 0
	Frame_V1              Frame_Version = 1
)

// Enum value maps for Frame_Version.
var (
	Frame_Version_name = map[int32]string{
		0: "UNKNOWN_VERSION",
		1: "V1",
	}
	Frame_Version_value = map[string]int32{
		"UNKNOWN_VERSION": 0,
		"V1":              1,
	}
)

func (x Frame_Version) Enum() *Frame_Version {
	p := new(Frame_Version)
	*p = x
	return p
}

func (x Frame_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frame_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[3].Descriptor()
}

func (Frame_Version) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[3]
}

func (x Frame_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Frame_Version) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Frame_Version(num)
	return nil
}

// Deprecated: Use Frame_Version.Descriptor instead.
func (Frame_Version) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{5, 0}
}

type V1Frame_FrameType int32

const (
	V1Frame_UNKNOWN_FRAME_TYPE    V1Frame_FrameType = 0
	V1Frame_INTRODUCTION          V1Frame_FrameType = 1
	V1Frame_RESPONSE              V1Frame_FrameType = 2
	V1Frame_PAIRED_KEY_ENCRYPTION V1Frame_FrameType = 3
	V1Frame_PAIRED_KEY_RESULT     V1Frame_FrameType = 4
	// No longer used.
	V1Frame_CERTIFICATE_INFO V1Frame_FrameType = 5
	V1Frame_CANCEL           V1Frame_FrameType = 6
	// No longer used.
	V1Frame_PROGRESS_UPDATE V1Frame_FrameType = 7
)

// Enum value maps for V1Frame_FrameType.
var (
	V1Frame_FrameType_name = map[int32]string{
		0: "UNKNOWN_FRAME_TYPE",
		1: "INTRODUCTION",
		2: "RESPONSE",
		3: "PAIRED_KEY_ENCRYPTION",
		4: "PAIRED_KEY_RESULT",
		5: "CERTIFICATE_INFO",
		6: "CANCEL",
		7: "PROGRESS_UPDATE",
	}
	V1Frame_FrameType_value = map[string]int32{
		"UNKNOWN_FRAME_TYPE":    0,
		"INTRODUCTION":          1,
		"RESPONSE":              2,
		"PAIRED_KEY_ENCRYPTION": 3,
		"PAIRED_KEY_RESULT":     4,
		"CERTIFICATE_INFO":      5,
		"CANCEL":                6,
		"PROGRESS_UPDATE":       7,
	}
)

func (x V1Frame_FrameType) Enum() *V1Frame_FrameType {
	p := new(V1Frame_FrameType)
	*p = x
	return p
}

func (x V1Frame_FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (V1Frame_FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[4].Descriptor()
}

func (V1Frame_FrameType) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[4]
}

func (x V1Frame_FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *V1Frame_FrameType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = V1Frame_FrameType(num)
	return nil
}

// Deprecated: Use V1Frame_FrameType.Descriptor instead.
func (V1Frame_FrameType) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{6, 0}
}

type IntroductionFrame_SharingUseCase int32

const (
	IntroductionFrame_UNKNOWN      IntroductionFrame_SharingUseCase = 0
	IntroductionFrame_NEARBY_SHARE IntroductionFrame_SharingUseCase = 1
	IntroductionFrame_REMOTE_COPY  IntroductionFrame_SharingUseCase = 2
)

// Enum value maps for IntroductionFrame_SharingUseCase.
var (
	IntroductionFrame_SharingUseCase_name = map[int32]string{
		0: "UNKNOWN",
		1: "NEARBY_SHARE",
		2: "REMOTE_COPY",
	}
	IntroductionFrame_SharingUseCase_value = map[string]int32{
		"UNKNOWN":      0,
		"NEARBY_SHARE": 1,
		"REMOTE_COPY":  2,
	}
)

func (x IntroductionFrame_SharingUseCase) Enum() *IntroductionFrame_SharingUseCase {
	p := new(IntroductionFrame_SharingUseCase)
	*p = x
	return p
}

func (x IntroductionFrame_SharingUseCase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntroductionFrame_SharingUseCase) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[5].Descriptor()
}

func (IntroductionFrame_SharingUseCase) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[5]
}

func (x IntroductionFrame_SharingUseCase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IntroductionFrame_SharingUseCase) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IntroductionFrame_SharingUseCase(num)
	return nil
}

// Deprecated: Use IntroductionFrame_SharingUseCase.Descriptor instead.
func (IntroductionFrame_SharingUseCase) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{7, 0}
}

type ConnectionResponseFrame_Status int32

const (
	ConnectionResponseFrame_UNKNOWN                     ConnectionResponseFrame_Status = 0
	ConnectionResponseFrame_ACCEPT                      ConnectionResponseFrame_Status = 1
	ConnectionResponseFrame_REJECT                      ConnectionResponseFrame_Status = 2
	ConnectionResponseFrame_NOT_ENOUGH_SPACE            ConnectionResponseFrame_Status = 3
	ConnectionResponseFrame_UNSUPPORTED_ATTACHMENT_TYPE ConnectionResponseFrame_Status = 4
	ConnectionResponseFrame_TIMED_OUT                   ConnectionResponseFrame_Status = 5
)

// Enum value maps for ConnectionResponseFrame_Status.
var (
	ConnectionResponseFrame_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACCEPT",
		2: "REJECT",
		3: "NOT_ENOUGH_SPACE",
		4: "UNSUPPORTED_ATTACHMENT_TYPE",
		5: "TIMED_OUT",
	}
	ConnectionResponseFrame_Status_value = map[string]int32{
		"UNKNOWN":                     0,
		"ACCEPT":                      1,
		"REJECT":                      2,
		"NOT_ENOUGH_SPACE":            3,
		"UNSUPPORTED_ATTACHMENT_TYPE": 4,
		"TIMED_OUT":                   5,
	}
)

func (x ConnectionResponseFrame_Status) Enum() *ConnectionResponseFrame_Status {
	p := new(ConnectionResponseFrame_Status)
	*p = x
	return p
}

func (x ConnectionResponseFrame_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionResponseFrame_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[6].Descriptor()
}

func (ConnectionResponseFrame_Status) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[6]
}

func (x ConnectionResponseFrame_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ConnectionResponseFrame_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ConnectionResponseFrame_Status(num)
	return nil
}

// Deprecated: Use ConnectionResponseFrame_Status.Descriptor instead.
func (ConnectionResponseFrame_Status) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{9, 0}
}

// LINT.IfChange
type AttachmentDetails_Type int32

const (
	AttachmentDetails_UNKNOWN AttachmentDetails_Type = 0
	// Represents FileAttachment.
	AttachmentDetails_FILE AttachmentDetails_Type = 1
	// Represents TextAttachment.
	AttachmentDetails_TEXT AttachmentDetails_Type = 2
	// Represents WifiCredentialsAttachment.
	AttachmentDetails_WIFI_CREDENTIALS AttachmentDetails_Type = 3
	// Represents AppAttachment.
	AttachmentDetails_APP AttachmentDetails_Type = 4
	// Represents StreamAttachment.
	AttachmentDetails_STREAM AttachmentDetails_Type = 5
)

// Enum value maps for AttachmentDetails_Type.
var (
	AttachmentDetails_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "FILE",
		2: "TEXT",
		3: "WIFI_CREDENTIALS",
		4: "APP",
		5: "STREAM",
	}
	AttachmentDetails_Type_value = map[string]int32{
		"UNKNOWN":          0,
		"FILE":             1,
		"TEXT":             2,
		"WIFI_CREDENTIALS": 3,
		"APP":              4,
		"STREAM":           5,
	}
)

func (x AttachmentDetails_Type) Enum() *AttachmentDetails_Type {
	p := new(AttachmentDetails_Type)
	*p = x
	return p
}

func (x AttachmentDetails_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentDetails_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[7].Descriptor()
}

func (AttachmentDetails_Type) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[7]
}

func (x AttachmentDetails_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AttachmentDetails_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AttachmentDetails_Type(num)
	return nil
}

// Deprecated: Use AttachmentDetails_Type.Descriptor instead.
func (AttachmentDetails_Type) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{10, 0}
}

type PairedKeyResultFrame_Status int32

const (
	PairedKeyResultFrame_UNKNOWN PairedKeyResultFrame_Status = 0
	PairedKeyResultFrame_SUCCESS PairedKeyResultFrame_Status = 1
	PairedKeyResultFrame_FAIL    PairedKeyResultFrame_Status = 2
	PairedKeyResultFrame_UNABLE  PairedKeyResultFrame_Status = 3
)

// Enum value maps for PairedKeyResultFrame_Status.
var (
	PairedKeyResultFrame_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAIL",
		3: "UNABLE",
	}
	PairedKeyResultFrame_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAIL":    2,
		"UNABLE":  3,
	}
)

func (x PairedKeyResultFrame_Status) Enum() *PairedKeyResultFrame_Status {
	p := new(PairedKeyResultFrame_Status)
	*p = x
	return p
}

func (x PairedKeyResultFrame_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PairedKeyResultFrame_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_format_proto_enumTypes[8].Descriptor()
}

func (PairedKeyResultFrame_Status) Type() protoreflect.EnumType {
	return &file_wire_format_proto_enumTypes[8]
}

func (x PairedKeyResultFrame_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PairedKeyResultFrame_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PairedKeyResultFrame_Status(num)
	return nil
}

// Deprecated: Use PairedKeyResultFrame_Status.Descriptor instead.
func (PairedKeyResultFrame_Status) EnumDescriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{15, 0}
}

// File metadata. Does not include the actual bytes of the file.
// NEXT_ID=10
type FileMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The human readable name of this file (eg. 'Cookbook.pdf').
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The type of file (eg. 'IMAGE' from 'dog.jpg'). Specifying a type helps
	// provide a richer experience on the receiving side.
	Type *FileMetadata_Type `protobuf:"varint,2,opt,name=type,enum=sharing.nearby.FileMetadata_Type,def=0" json:"type,omitempty"`
	// The FILE payload id that will be sent as a follow up containing the actual
	// bytes of the file.
	PayloadId *int64 `protobuf:"varint,3,opt,name=payload_id,json=payloadId" json:"payload_id,omitempty"`
	// The total size of the file.
	Size *int64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	// The mimeType of file (eg. 'image/jpeg' from 'dog.jpg'). Specifying a
	// mimeType helps provide a richer experience on receiving side.
	MimeType *string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,def=application/octet-stream" json:"mime_type,omitempty"`
	// A uuid for the attachment. Should be unique across all attachments.
	Id *int64 `protobuf:"varint,6,opt,name=id" json:"id,omitempty"`
	// The parent folder.
	ParentFolder *string `protobuf:"bytes,7,opt,name=parent_folder,json=parentFolder" json:"parent_folder,omitempty"`
	// A stable identifier for the attachment. Used for receiver to identify same
	// attachment from different transfers.
	AttachmentHash *int64 `protobuf:"varint,8,opt,name=attachment_hash,json=attachmentHash" json:"attachment_hash,omitempty"`
	// True, if image in file attachment is sensitive
	IsSensitiveContent *bool `protobuf:"varint,9,opt,name=is_sensitive_content,json=isSensitiveContent" json:"is_sensitive_content,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for FileMetadata fields.
const (
	Default_FileMetadata_Type     = FileMetadata_UNKNOWN
	Default_FileMetadata_MimeType = string("application/octet-stream")
)

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_wire_format_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FileMetadata) GetType() FileMetadata_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_FileMetadata_Type
}

func (x *FileMetadata) GetPayloadId() int64 {
	if x != nil && x.PayloadId != nil {
		return *x.PayloadId
	}
	return 0
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *FileMetadata) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return Default_FileMetadata_MimeType
}

func (x *FileMetadata) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *FileMetadata) GetParentFolder() string {
	if x != nil && x.ParentFolder != nil {
		return *x.ParentFolder
	}
	return ""
}

func (x *FileMetadata) GetAttachmentHash() int64 {
	if x != nil && x.AttachmentHash != nil {
		return *x.AttachmentHash
	}
	return 0
}

func (x *FileMetadata) GetIsSensitiveContent() bool {
	if x != nil && x.IsSensitiveContent != nil {
		return *x.IsSensitiveContent
	}
	return false
}

// NEXT_ID=8
type TextMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The title of the text content.
	TextTitle *string `protobuf:"bytes,2,opt,name=text_title,json=textTitle" json:"text_title,omitempty"`
	// The type of text (phone number, url, address, or plain text).
	Type *TextMetadata_Type `protobuf:"varint,3,opt,name=type,enum=sharing.nearby.TextMetadata_Type,def=0" json:"type,omitempty"`
	// The BYTE payload id that will be sent as a follow up containing the actual
	// bytes of the text.
	PayloadId *int64 `protobuf:"varint,4,opt,name=payload_id,json=payloadId" json:"payload_id,omitempty"`
	// The size of the text content.
	Size *int64 `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	// A uuid for the attachment. Should be unique across all attachments.
	Id *int64 `protobuf:"varint,6,opt,name=id" json:"id,omitempty"`
	// True if text is sensitive, e.g. password
	IsSensitiveText *bool `protobuf:"varint,7,opt,name=is_sensitive_text,json=isSensitiveText" json:"is_sensitive_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for TextMetadata fields.
const (
	Default_TextMetadata_Type = TextMetadata_UNKNOWN
)

func (x *TextMetadata) Reset() {
	*x = TextMetadata{}
	mi := &file_wire_format_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMetadata) ProtoMessage() {}

func (x *TextMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMetadata.ProtoReflect.Descriptor instead.
func (*TextMetadata) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{1}
}

func (x *TextMetadata) GetTextTitle() string {
	if x != nil && x.TextTitle != nil {
		return *x.TextTitle
	}
	return ""
}

func (x *TextMetadata) GetType() TextMetadata_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_TextMetadata_Type
}

func (x *TextMetadata) GetPayloadId() int64 {
	if x != nil && x.PayloadId != nil {
		return *x.PayloadId
	}
	return 0
}

func (x *TextMetadata) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *TextMetadata) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TextMetadata) GetIsSensitiveText() bool {
	if x != nil && x.IsSensitiveText != nil {
		return *x.IsSensitiveText
	}
	return false
}

// NEXT_ID=6
type WifiCredentialsMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Wifi network name. This will be sent in introduction.
	Ssid *string `protobuf:"bytes,2,opt,name=ssid" json:"ssid,omitempty"`
	// The security type of network (OPEN, WPA_PSK, WEP).
	SecurityType *WifiCredentialsMetadata_SecurityType `protobuf:"varint,3,opt,name=security_type,json=securityType,enum=sharing.nearby.WifiCredentialsMetadata_SecurityType,def=0" json:"security_type,omitempty"`
	// The BYTE payload id that will be sent as a follow up containing the
	// password.
	PayloadId *int64 `protobuf:"varint,4,opt,name=payload_id,json=payloadId" json:"payload_id,omitempty"`
	// A uuid for the attachment. Should be unique across all attachments.
	Id            *int64 `protobuf:"varint,5,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for WifiCredentialsMetadata fields.
const (
	Default_WifiCredentialsMetadata_SecurityType = WifiCredentialsMetadata_UNKNOWN_SECURITY_TYPE
)

func (x *WifiCredentialsMetadata) Reset() {
	*x = WifiCredentialsMetadata{}
	mi := &file_wire_format_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiCredentialsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiCredentialsMetadata) ProtoMessage() {}

func (x *WifiCredentialsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiCredentialsMetadata.ProtoReflect.Descriptor instead.
func (*WifiCredentialsMetadata) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{2}
}

func (x *WifiCredentialsMetadata) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *WifiCredentialsMetadata) GetSecurityType() WifiCredentialsMetadata_SecurityType {
	if x != nil && x.SecurityType != nil {
		return *x.SecurityType
	}
	return Default_WifiCredentialsMetadata_SecurityType
}

func (x *WifiCredentialsMetadata) GetPayloadId() int64 {
	if x != nil && x.PayloadId != nil {
		return *x.PayloadId
	}
	return 0
}

func (x *WifiCredentialsMetadata) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

// NEXT_ID=8
type AppMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The app name. This will be sent in introduction.
	AppName *string `protobuf:"bytes,1,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	// The size of the all split of apks.
	Size *int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	// The File payload id that will be sent as a follow up containing the
	// apk paths.
	PayloadId []int64 `protobuf:"varint,3,rep,packed,name=payload_id,json=payloadId" json:"payload_id,omitempty"`
	// A uuid for the attachment. Should be unique across all attachments.
	Id *int64 `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	// The name of apk file. This will be sent in introduction.
	FileName []string `protobuf:"bytes,5,rep,name=file_name,json=fileName" json:"file_name,omitempty"`
	// The size of apk file. This will be sent in introduction.
	FileSize []int64 `protobuf:"varint,6,rep,packed,name=file_size,json=fileSize" json:"file_size,omitempty"`
	// The package name. This will be sent in introduction.
	PackageName   *string `protobuf:"bytes,7,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMetadata) Reset() {
	*x = AppMetadata{}
	mi := &file_wire_format_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMetadata) ProtoMessage() {}

func (x *AppMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMetadata.ProtoReflect.Descriptor instead.
func (*AppMetadata) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{3}
}

func (x *AppMetadata) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *AppMetadata) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *AppMetadata) GetPayloadId() []int64 {
	if x != nil {
		return x.PayloadId
	}
	return nil
}

func (x *AppMetadata) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AppMetadata) GetFileName() []string {
	if x != nil {
		return x.FileName
	}
	return nil
}

func (x *AppMetadata) GetFileSize() []int64 {
	if x != nil {
		return x.FileSize
	}
	return nil
}

func (x *AppMetadata) GetPackageName() string {
	if x != nil && x.PackageName != nil {
		return *x.PackageName
	}
	return ""
}

// NEXT_ID=5
type StreamMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human readable description for the stream.
	Description *string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// The package name of the sending application.
	PackageName *string `protobuf:"bytes,2,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	// The <TYPE> payload id that will be send as a followup containing the
	// ParcelFileDescriptor.
	PayloadId *int64 `protobuf:"varint,3,opt,name=payload_id,json=payloadId" json:"payload_id,omitempty"`
	// The human-readable name of the package that should be displayed as
	// attribution if no other information is available (i.e. the package is not
	// installed locally yet).
	AttributedAppName *string `protobuf:"bytes,4,opt,name=attributed_app_name,json=attributedAppName" json:"attributed_app_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_wire_format_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetadata.ProtoReflect.Descriptor instead.
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *StreamMetadata) GetPackageName() string {
	if x != nil && x.PackageName != nil {
		return *x.PackageName
	}
	return ""
}

func (x *StreamMetadata) GetPayloadId() int64 {
	if x != nil && x.PayloadId != nil {
		return *x.PayloadId
	}
	return 0
}

func (x *StreamMetadata) GetAttributedAppName() string {
	if x != nil && x.AttributedAppName != nil {
		return *x.AttributedAppName
	}
	return ""
}

// A frame used when sending messages over the wire.
// NEXT_ID=3
type Frame struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *Frame_Version         `protobuf:"varint,1,opt,name=version,enum=sharing.nearby.Frame_Version" json:"version,omitempty"`
	// Right now there's only 1 version, but if there are more, exactly one of
	// the following fields will be set.
	V1            *V1Frame `protobuf:"bytes,2,opt,name=v1" json:"v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_wire_format_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetVersion() Frame_Version {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Frame_UNKNOWN_VERSION
}

func (x *Frame) GetV1() *V1Frame {
	if x != nil {
		return x.V1
	}
	return nil
}

// NEXT_ID=8
type V1Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  *V1Frame_FrameType     `protobuf:"varint,1,opt,name=type,enum=sharing.nearby.V1Frame_FrameType" json:"type,omitempty"`
	// At most one of the following fields will be set.
	Introduction        *IntroductionFrame        `protobuf:"bytes,2,opt,name=introduction" json:"introduction,omitempty"`
	ConnectionResponse  *ConnectionResponseFrame  `protobuf:"bytes,3,opt,name=connection_response,json=connectionResponse" json:"connection_response,omitempty"`
	PairedKeyEncryption *PairedKeyEncryptionFrame `protobuf:"bytes,4,opt,name=paired_key_encryption,json=pairedKeyEncryption" json:"paired_key_encryption,omitempty"`
	PairedKeyResult     *PairedKeyResultFrame     `protobuf:"bytes,5,opt,name=paired_key_result,json=pairedKeyResult" json:"paired_key_result,omitempty"`
	// Deprecated: Marked as deprecated in wire_format.proto.
	CertificateInfo *CertificateInfoFrame `protobuf:"bytes,6,opt,name=certificate_info,json=certificateInfo" json:"certificate_info,omitempty"`
	// Deprecated: Marked as deprecated in wire_format.proto.
	ProgressUpdate *ProgressUpdateFrame `protobuf:"bytes,7,opt,name=progress_update,json=progressUpdate" json:"progress_update,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *V1Frame) Reset() {
	*x = V1Frame{}
	mi := &file_wire_format_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1Frame) ProtoMessage() {}

func (x *V1Frame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1Frame.ProtoReflect.Descriptor instead.
func (*V1Frame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{6}
}

func (x *V1Frame) GetType() V1Frame_FrameType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return V1Frame_UNKNOWN_FRAME_TYPE
}

func (x *V1Frame) GetIntroduction() *IntroductionFrame {
	if x != nil {
		return x.Introduction
	}
	return nil
}

func (x *V1Frame) GetConnectionResponse() *ConnectionResponseFrame {
	if x != nil {
		return x.ConnectionResponse
	}
	return nil
}

func (x *V1Frame) GetPairedKeyEncryption() *PairedKeyEncryptionFrame {
	if x != nil {
		return x.PairedKeyEncryption
	}
	return nil
}

func (x *V1Frame) GetPairedKeyResult() *PairedKeyResultFrame {
	if x != nil {
		return x.PairedKeyResult
	}
	return nil
}

// Deprecated: Marked as deprecated in wire_format.proto.
func (x *V1Frame) GetCertificateInfo() *CertificateInfoFrame {
	if x != nil {
		return x.CertificateInfo
	}
	return nil
}

// Deprecated: Marked as deprecated in wire_format.proto.
func (x *V1Frame) GetProgressUpdate() *ProgressUpdateFrame {
	if x != nil {
		return x.ProgressUpdate
	}
	return nil
}

// An introduction packet sent by the sending side. Contains a list of files
// they'd like to share.
// NEXT_ID=10
type IntroductionFrame struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FileMetadata []*FileMetadata        `protobuf:"bytes,1,rep,name=file_metadata,json=fileMetadata" json:"file_metadata,omitempty"`
	TextMetadata []*TextMetadata        `protobuf:"bytes,2,rep,name=text_metadata,json=textMetadata" json:"text_metadata,omitempty"`
	// The required app package to open the content. May be null.
	RequiredPackage         *string                           `protobuf:"bytes,3,opt,name=required_package,json=requiredPackage" json:"required_package,omitempty"`
	WifiCredentialsMetadata []*WifiCredentialsMetadata        `protobuf:"bytes,4,rep,name=wifi_credentials_metadata,json=wifiCredentialsMetadata" json:"wifi_credentials_metadata,omitempty"`
	AppMetadata             []*AppMetadata                    `protobuf:"bytes,5,rep,name=app_metadata,json=appMetadata" json:"app_metadata,omitempty"`
	StartTransfer           *bool                             `protobuf:"varint,6,opt,name=start_transfer,json=startTransfer" json:"start_transfer,omitempty"`
	StreamMetadata          []*StreamMetadata                 `protobuf:"bytes,7,rep,name=stream_metadata,json=streamMetadata" json:"stream_metadata,omitempty"`
	UseCase                 *IntroductionFrame_SharingUseCase `protobuf:"varint,8,opt,name=use_case,json=useCase,enum=sharing.nearby.IntroductionFrame_SharingUseCase" json:"use_case,omitempty"`
	PreviewPayloadIds       []int64                           `protobuf:"varint,9,rep,name=preview_payload_ids,json=previewPayloadIds" json:"preview_payload_ids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *IntroductionFrame) Reset() {
	*x = IntroductionFrame{}
	mi := &file_wire_format_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntroductionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionFrame) ProtoMessage() {}

func (x *IntroductionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionFrame.ProtoReflect.Descriptor instead.
func (*IntroductionFrame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{7}
}

func (x *IntroductionFrame) GetFileMetadata() []*FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

func (x *IntroductionFrame) GetTextMetadata() []*TextMetadata {
	if x != nil {
		return x.TextMetadata
	}
	return nil
}

func (x *IntroductionFrame) GetRequiredPackage() string {
	if x != nil && x.RequiredPackage != nil {
		return *x.RequiredPackage
	}
	return ""
}

func (x *IntroductionFrame) GetWifiCredentialsMetadata() []*WifiCredentialsMetadata {
	if x != nil {
		return x.WifiCredentialsMetadata
	}
	return nil
}

func (x *IntroductionFrame) GetAppMetadata() []*AppMetadata {
	if x != nil {
		return x.AppMetadata
	}
	return nil
}

func (x *IntroductionFrame) GetStartTransfer() bool {
	if x != nil && x.StartTransfer != nil {
		return *x.StartTransfer
	}
	return false
}

func (x *IntroductionFrame) GetStreamMetadata() []*StreamMetadata {
	if x != nil {
		return x.StreamMetadata
	}
	return nil
}

func (x *IntroductionFrame) GetUseCase() IntroductionFrame_SharingUseCase {
	if x != nil && x.UseCase != nil {
		return *x.UseCase
	}
	return IntroductionFrame_UNKNOWN
}

func (x *IntroductionFrame) GetPreviewPayloadIds() []int64 {
	if x != nil {
		return x.PreviewPayloadIds
	}
	return nil
}

// A progress update packet sent by the sending side. Contains transfer progress
// value. NEXT_ID=3
type ProgressUpdateFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Progress *float32               `protobuf:"fixed32,1,opt,name=progress" json:"progress,omitempty"`
	// True, if the receiver should start bandwidth upgrade and receiving the
	// payloads.
	StartTransfer *bool `protobuf:"varint,2,opt,name=start_transfer,json=startTransfer" json:"start_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdateFrame) Reset() {
	*x = ProgressUpdateFrame{}
	mi := &file_wire_format_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateFrame) ProtoMessage() {}

func (x *ProgressUpdateFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateFrame.ProtoReflect.Descriptor instead.
func (*ProgressUpdateFrame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressUpdateFrame) GetProgress() float32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *ProgressUpdateFrame) GetStartTransfer() bool {
	if x != nil && x.StartTransfer != nil {
		return *x.StartTransfer
	}
	return false
}

// A response packet sent by the receiving side. Accepts or rejects the list of
// files.
// NEXT_ID=4
type ConnectionResponseFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The receiving side's response.
	Status *ConnectionResponseFrame_Status `protobuf:"varint,1,opt,name=status,enum=sharing.nearby.ConnectionResponseFrame_Status" json:"status,omitempty"`
	// Key is attachment hash, value is the details of attachment.
	AttachmentDetails map[int64]*AttachmentDetails `protobuf:"bytes,2,rep,name=attachment_details,json=attachmentDetails" json:"attachment_details,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// In the case of a stream attachments, the other side of the pipe.
	// Both sender and receiver should validate matching counts.
	StreamMetadata []*StreamMetadata `protobuf:"bytes,3,rep,name=stream_metadata,json=streamMetadata" json:"stream_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionResponseFrame) Reset() {
	*x = ConnectionResponseFrame{}
	mi := &file_wire_format_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponseFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponseFrame) ProtoMessage() {}

func (x *ConnectionResponseFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponseFrame.ProtoReflect.Descriptor instead.
func (*ConnectionResponseFrame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionResponseFrame) GetStatus() ConnectionResponseFrame_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ConnectionResponseFrame_UNKNOWN
}

func (x *ConnectionResponseFrame) GetAttachmentDetails() map[int64]*AttachmentDetails {
	if x != nil {
		return x.AttachmentDetails
	}
	return nil
}

func (x *ConnectionResponseFrame) GetStreamMetadata() []*StreamMetadata {
	if x != nil {
		return x.StreamMetadata
	}
	return nil
}

// Attachment details that sent in ConnectionResponseFrame.
// NEXT_ID=3
type AttachmentDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attachment family type.
	Type *AttachmentDetails_Type `protobuf:"varint,1,opt,name=type,enum=sharing.nearby.AttachmentDetails_Type" json:"type,omitempty"`
	// This field is only for FILE type.
	FileAttachmentDetails *FileAttachmentDetails `protobuf:"bytes,2,opt,name=file_attachment_details,json=fileAttachmentDetails" json:"file_attachment_details,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AttachmentDetails) Reset() {
	*x = AttachmentDetails{}
	mi := &file_wire_format_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentDetails) ProtoMessage() {}

func (x *AttachmentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentDetails.ProtoReflect.Descriptor instead.
func (*AttachmentDetails) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{10}
}

func (x *AttachmentDetails) GetType() AttachmentDetails_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AttachmentDetails_UNKNOWN
}

func (x *AttachmentDetails) GetFileAttachmentDetails() *FileAttachmentDetails {
	if x != nil {
		return x.FileAttachmentDetails
	}
	return nil
}

// File attachment details included in ConnectionResponseFrame.
// NEXT_ID=3
type FileAttachmentDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existing local file size on receiver side.
	ReceiverExistingFileSize *int64 `protobuf:"varint,1,opt,name=receiver_existing_file_size,json=receiverExistingFileSize" json:"receiver_existing_file_size,omitempty"`
	// The key is attachment hash, a stable identifier for the attachment.
	// Value is list of payload details transferred for the attachment.
	AttachmentHashPayloads map[int64]*PayloadsDetails `protobuf:"bytes,2,rep,name=attachment_hash_payloads,json=attachmentHashPayloads" json:"attachment_hash_payloads,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileAttachmentDetails) Reset() {
	*x = FileAttachmentDetails{}
	mi := &file_wire_format_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttachmentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttachmentDetails) ProtoMessage() {}

func (x *FileAttachmentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttachmentDetails.ProtoReflect.Descriptor instead.
func (*FileAttachmentDetails) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{11}
}

func (x *FileAttachmentDetails) GetReceiverExistingFileSize() int64 {
	if x != nil && x.ReceiverExistingFileSize != nil {
		return *x.ReceiverExistingFileSize
	}
	return 0
}

func (x *FileAttachmentDetails) GetAttachmentHashPayloads() map[int64]*PayloadsDetails {
	if x != nil {
		return x.AttachmentHashPayloads
	}
	return nil
}

// NEXT_ID=2
type PayloadsDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list should be sorted by creation timestamp.
	PayloadDetails []*PayloadDetails `protobuf:"bytes,1,rep,name=payload_details,json=payloadDetails" json:"payload_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PayloadsDetails) Reset() {
	*x = PayloadsDetails{}
	mi := &file_wire_format_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadsDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadsDetails) ProtoMessage() {}

func (x *PayloadsDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadsDetails.ProtoReflect.Descriptor instead.
func (*PayloadsDetails) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{12}
}

func (x *PayloadsDetails) GetPayloadDetails() []*PayloadDetails {
	if x != nil {
		return x.PayloadDetails
	}
	return nil
}

// Metadata of a payload file created by Nearby Connections.
// NEXT_ID=4
type PayloadDetails struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CreationTimestampMillis *int64                 `protobuf:"varint,2,opt,name=creation_timestamp_millis,json=creationTimestampMillis" json:"creation_timestamp_millis,omitempty"`
	Size                    *int64                 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PayloadDetails) Reset() {
	*x = PayloadDetails{}
	mi := &file_wire_format_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadDetails) ProtoMessage() {}

func (x *PayloadDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadDetails.ProtoReflect.Descriptor instead.
func (*PayloadDetails) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{13}
}

func (x *PayloadDetails) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PayloadDetails) GetCreationTimestampMillis() int64 {
	if x != nil && x.CreationTimestampMillis != nil {
		return *x.CreationTimestampMillis
	}
	return 0
}

func (x *PayloadDetails) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

// A paired key encryption packet sent between devices, contains signed data.
// NEXT_ID=5
type PairedKeyEncryptionFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The encrypted data in byte array format.
	SignedData []byte `protobuf:"bytes,1,opt,name=signed_data,json=signedData" json:"signed_data,omitempty"`
	// The hash of a certificate id.
	SecretIdHash []byte `protobuf:"bytes,2,opt,name=secret_id_hash,json=secretIdHash" json:"secret_id_hash,omitempty"`
	// An optional encrypted data in byte array format.
	OptionalSignedData []byte `protobuf:"bytes,3,opt,name=optional_signed_data,json=optionalSignedData" json:"optional_signed_data,omitempty"`
	// An optional QR code handshake data in a byte array format.
	// For incoming connection contains a signature of the UKEY2
	// token, created with the sender's private key.
	// For outgoing connection contains an HKDF of the connection token and of the
	// UKEY2 token
	QrCodeHandshakeData []byte `protobuf:"bytes,4,opt,name=qr_code_handshake_data,json=qrCodeHandshakeData" json:"qr_code_handshake_data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PairedKeyEncryptionFrame) Reset() {
	*x = PairedKeyEncryptionFrame{}
	mi := &file_wire_format_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairedKeyEncryptionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairedKeyEncryptionFrame) ProtoMessage() {}

func (x *PairedKeyEncryptionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairedKeyEncryptionFrame.ProtoReflect.Descriptor instead.
func (*PairedKeyEncryptionFrame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{14}
}

func (x *PairedKeyEncryptionFrame) GetSignedData() []byte {
	if x != nil {
		return x.SignedData
	}
	return nil
}

func (x *PairedKeyEncryptionFrame) GetSecretIdHash() []byte {
	if x != nil {
		return x.SecretIdHash
	}
	return nil
}

func (x *PairedKeyEncryptionFrame) GetOptionalSignedData() []byte {
	if x != nil {
		return x.OptionalSignedData
	}
	return nil
}

func (x *PairedKeyEncryptionFrame) GetQrCodeHandshakeData() []byte {
	if x != nil {
		return x.QrCodeHandshakeData
	}
	return nil
}

// A paired key verification result packet sent between devices.
// NEXT_ID=3
type PairedKeyResultFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The verification result.
	Status *PairedKeyResultFrame_Status `protobuf:"varint,1,opt,name=status,enum=sharing.nearby.PairedKeyResultFrame_Status" json:"status,omitempty"`
	// OS type.
	OsType        *sharingenums.OSType `protobuf:"varint,2,opt,name=os_type,json=osType,enum=location.nearby.proto.sharing.OSType" json:"os_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairedKeyResultFrame) Reset() {
	*x = PairedKeyResultFrame{}
	mi := &file_wire_format_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairedKeyResultFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairedKeyResultFrame) ProtoMessage() {}

func (x *PairedKeyResultFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairedKeyResultFrame.ProtoReflect.Descriptor instead.
func (*PairedKeyResultFrame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{15}
}

func (x *PairedKeyResultFrame) GetStatus() PairedKeyResultFrame_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PairedKeyResultFrame_UNKNOWN
}

func (x *PairedKeyResultFrame) GetOsType() sharingenums.OSType {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return sharingenums.OSType(0)
}

// A package containing certificate info to be shared to remote device offline.
// NEXT_ID=2
type CertificateInfoFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public certificates to be shared with remote devices.
	PublicCertificate []*PublicCertificate `protobuf:"bytes,1,rep,name=public_certificate,json=publicCertificate" json:"public_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CertificateInfoFrame) Reset() {
	*x = CertificateInfoFrame{}
	mi := &file_wire_format_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfoFrame) ProtoMessage() {}

func (x *CertificateInfoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfoFrame.ProtoReflect.Descriptor instead.
func (*CertificateInfoFrame) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{16}
}

func (x *CertificateInfoFrame) GetPublicCertificate() []*PublicCertificate {
	if x != nil {
		return x.PublicCertificate
	}
	return nil
}

// A public certificate from the local device.
// NEXT_ID=8
type PublicCertificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique id of the public certificate.
	SecretId []byte `protobuf:"bytes,1,opt,name=secret_id,json=secretId" json:"secret_id,omitempty"`
	// A bytes representation of a Secret Key owned by contact, to decrypt the
	// metadata_key stored within the advertisement.
	AuthenticityKey []byte `protobuf:"bytes,2,opt,name=authenticity_key,json=authenticityKey" json:"authenticity_key,omitempty"`
	// A bytes representation a public key of X509Certificate, owned by contact,
	// to decrypt encrypted UKEY2 (from Nearby Connections API) as a hand shake in
	// contact verification phase.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	// The time in millis from epoch when this certificate becomes effective.
	StartTime *int64 `protobuf:"varint,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	// The time in millis from epoch when this certificate expires.
	EndTime *int64 `protobuf:"varint,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	// The encrypted metadata in bytes, contains personal information of the
	// device/user who created this certificate. Needs to be decrypted into bytes,
	// and converted back to EncryptedMetadata object to access fields.
	EncryptedMetadataBytes []byte `protobuf:"bytes,6,opt,name=encrypted_metadata_bytes,json=encryptedMetadataBytes" json:"encrypted_metadata_bytes,omitempty"`
	// The tag for verifying metadata_encryption_key.
	MetadataEncryptionKeyTag []byte `protobuf:"bytes,7,opt,name=metadata_encryption_key_tag,json=metadataEncryptionKeyTag" json:"metadata_encryption_key_tag,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PublicCertificate) Reset() {
	*x = PublicCertificate{}
	mi := &file_wire_format_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicCertificate) ProtoMessage() {}

func (x *PublicCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicCertificate.ProtoReflect.Descriptor instead.
func (*PublicCertificate) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{17}
}

func (x *PublicCertificate) GetSecretId() []byte {
	if x != nil {
		return x.SecretId
	}
	return nil
}

func (x *PublicCertificate) GetAuthenticityKey() []byte {
	if x != nil {
		return x.AuthenticityKey
	}
	return nil
}

func (x *PublicCertificate) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PublicCertificate) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *PublicCertificate) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *PublicCertificate) GetEncryptedMetadataBytes() []byte {
	if x != nil {
		return x.EncryptedMetadataBytes
	}
	return nil
}

func (x *PublicCertificate) GetMetadataEncryptionKeyTag() []byte {
	if x != nil {
		return x.MetadataEncryptionKeyTag
	}
	return nil
}

// NEXT_ID=3
type WifiCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wi-Fi password.
	Password *string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	// True if the network is a hidden network that is not broadcasting its SSID.
	// Default is false.
	HiddenSsid    *bool `protobuf:"varint,2,opt,name=hidden_ssid,json=hiddenSsid,def=0" json:"hidden_ssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for WifiCredentials fields.
const (
	Default_WifiCredentials_HiddenSsid = bool(false)
)

func (x *WifiCredentials) Reset() {
	*x = WifiCredentials{}
	mi := &file_wire_format_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiCredentials) ProtoMessage() {}

func (x *WifiCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiCredentials.ProtoReflect.Descriptor instead.
func (*WifiCredentials) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{18}
}

func (x *WifiCredentials) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *WifiCredentials) GetHiddenSsid() bool {
	if x != nil && x.HiddenSsid != nil {
		return *x.HiddenSsid
	}
	return Default_WifiCredentials_HiddenSsid
}

// NEXT_ID=2
type StreamDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized ParcelFileDescriptor for input stream (for the receiver).
	InputStreamParcelFileDescriptorBytes []byte `protobuf:"bytes,1,opt,name=input_stream_parcel_file_descriptor_bytes,json=inputStreamParcelFileDescriptorBytes" json:"input_stream_parcel_file_descriptor_bytes,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *StreamDetails) Reset() {
	*x = StreamDetails{}
	mi := &file_wire_format_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDetails) ProtoMessage() {}

func (x *StreamDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wire_format_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDetails.ProtoReflect.Descriptor instead.
func (*StreamDetails) Descriptor() ([]byte, []int) {
	return file_wire_format_proto_rawDescGZIP(), []int{19}
}

func (x *StreamDetails) GetInputStreamParcelFileDescriptorBytes() []byte {
	if x != nil {
		return x.InputStreamParcelFileDescriptorBytes
	}
	return nil
}

var File_wire_format_proto protoreflect.FileDescriptor

const file_wire_format_proto_rawDesc = "" +
	"\n" +
	"\x11wire_format.proto\x12\x0esharing.nearby\x1a\x13sharing_enums.proto\"\xc3\x03\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2!.sharing.nearby.FileMetadata.Type:\aUNKNOWNR\x04type\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x03 \x01(\x03R\tpayloadId\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x125\n" +
	"\tmime_type\x18\x05 \x01(\t:\x18application/octet-streamR\bmimeType\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\x12#\n" +
	"\rparent_folder\x18\a \x01(\tR\fparentFolder\x12'\n" +
	"\x0fattachment_hash\x18\b \x01(\x03R\x0eattachmentHash\x120\n" +
	"\x14is_sensitive_content\x18\t \x01(\bR\x12isSensitiveContent\"e\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\x0f\n" +
	"\vANDROID_APP\x10\x03\x12\t\n" +
	"\x05AUDIO\x10\x04\x12\f\n" +
	"\bDOCUMENT\x10\x05\x12\x10\n" +
	"\fCONTACT_CARD\x10\x06\"\xa3\x02\n" +
	"\fTextMetadata\x12\x1d\n" +
	"\n" +
	"text_title\x18\x02 \x01(\tR\ttextTitle\x12>\n" +
	"\x04type\x18\x03 \x01(\x0e2!.sharing.nearby.TextMetadata.Type:\aUNKNOWNR\x04type\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x04 \x01(\x03R\tpayloadId\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\x12*\n" +
	"\x11is_sensitive_text\x18\a \x01(\bR\x0fisSensitiveText\"E\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\a\n" +
	"\x03URL\x10\x02\x12\v\n" +
	"\aADDRESS\x10\x03\x12\x10\n" +
	"\fPHONE_NUMBER\x10\x04\"\xa2\x02\n" +
	"\x17WifiCredentialsMetadata\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\tR\x04ssid\x12p\n" +
	"\rsecurity_type\x18\x03 \x01(\x0e24.sharing.nearby.WifiCredentialsMetadata.SecurityType:\x15UNKNOWN_SECURITY_TYPER\fsecurityType\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x04 \x01(\x03R\tpayloadId\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\"R\n" +
	"\fSecurityType\x12\x19\n" +
	"\x15UNKNOWN_SECURITY_TYPE\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\v\n" +
	"\aWPA_PSK\x10\x02\x12\a\n" +
	"\x03WEP\x10\x03\x12\a\n" +
	"\x03SAE\x10\x04\"\xd0\x01\n" +
	"\vAppMetadata\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\n" +
	"payload_id\x18\x03 \x03(\x03B\x02\x10\x01R\tpayloadId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfile_name\x18\x05 \x03(\tR\bfileName\x12\x1f\n" +
	"\tfile_size\x18\x06 \x03(\x03B\x02\x10\x01R\bfileSize\x12!\n" +
	"\fpackage_name\x18\a \x01(\tR\vpackageName\"\xa4\x01\n" +
	"\x0eStreamMetadata\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x03 \x01(\x03R\tpayloadId\x12.\n" +
	"\x13attributed_app_name\x18\x04 \x01(\tR\x11attributedAppName\"\x91\x01\n" +
	"\x05Frame\x127\n" +
	"\aversion\x18\x01 \x01(\x0e2\x1d.sharing.nearby.Frame.VersionR\aversion\x12'\n" +
	"\x02v1\x18\x02 \x01(\v2\x17.sharing.nearby.V1FrameR\x02v1\"&\n" +
	"\aVersion\x12\x13\n" +
	"\x0fUNKNOWN_VERSION\x10\x00\x12\x06\n" +
	"\x02V1\x10\x01\"\xe7\x05\n" +
	"\aV1Frame\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.sharing.nearby.V1Frame.FrameTypeR\x04type\x12E\n" +
	"\fintroduction\x18\x02 \x01(\v2!.sharing.nearby.IntroductionFrameR\fintroduction\x12X\n" +
	"\x13connection_response\x18\x03 \x01(\v2'.sharing.nearby.ConnectionResponseFrameR\x12connectionResponse\x12\\\n" +
	"\x15paired_key_encryption\x18\x04 \x01(\v2(.sharing.nearby.PairedKeyEncryptionFrameR\x13pairedKeyEncryption\x12P\n" +
	"\x11paired_key_result\x18\x05 \x01(\v2$.sharing.nearby.PairedKeyResultFrameR\x0fpairedKeyResult\x12S\n" +
	"\x10certificate_info\x18\x06 \x01(\v2$.sharing.nearby.CertificateInfoFrameB\x02\x18\x01R\x0fcertificateInfo\x12P\n" +
	"\x0fprogress_update\x18\a \x01(\v2#.sharing.nearby.ProgressUpdateFrameB\x02\x18\x01R\x0eprogressUpdate\"\xac\x01\n" +
	"\tFrameType\x12\x16\n" +
	"\x12UNKNOWN_FRAME_TYPE\x10\x00\x12\x10\n" +
	"\fINTRODUCTION\x10\x01\x12\f\n" +
	"\bRESPONSE\x10\x02\x12\x19\n" +
	"\x15PAIRED_KEY_ENCRYPTION\x10\x03\x12\x15\n" +
	"\x11PAIRED_KEY_RESULT\x10\x04\x12\x14\n" +
	"\x10CERTIFICATE_INFO\x10\x05\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x06\x12\x13\n" +
	"\x0fPROGRESS_UPDATE\x10\a\"\x98\x05\n" +
	"\x11IntroductionFrame\x12A\n" +
	"\rfile_metadata\x18\x01 \x03(\v2\x1c.sharing.nearby.FileMetadataR\ffileMetadata\x12A\n" +
	"\rtext_metadata\x18\x02 \x03(\v2\x1c.sharing.nearby.TextMetadataR\ftextMetadata\x12)\n" +
	"\x10required_package\x18\x03 \x01(\tR\x0frequiredPackage\x12c\n" +
	"\x19wifi_credentials_metadata\x18\x04 \x03(\v2'.sharing.nearby.WifiCredentialsMetadataR\x17wifiCredentialsMetadata\x12>\n" +
	"\fapp_metadata\x18\x05 \x03(\v2\x1b.sharing.nearby.AppMetadataR\vappMetadata\x12%\n" +
	"\x0estart_transfer\x18\x06 \x01(\bR\rstartTransfer\x12G\n" +
	"\x0fstream_metadata\x18\a \x03(\v2\x1e.sharing.nearby.StreamMetadataR\x0estreamMetadata\x12K\n" +
	"\buse_case\x18\b \x01(\x0e20.sharing.nearby.IntroductionFrame.SharingUseCaseR\auseCase\x12.\n" +
	"\x13preview_payload_ids\x18\t \x03(\x03R\x11previewPayloadIds\"@\n" +
	"\x0eSharingUseCase\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fNEARBY_SHARE\x10\x01\x12\x0f\n" +
	"\vREMOTE_COPY\x10\x02\"X\n" +
	"\x13ProgressUpdateFrame\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x02R\bprogress\x12%\n" +
	"\x0estart_transfer\x18\x02 \x01(\bR\rstartTransfer\"\xf7\x03\n" +
	"\x17ConnectionResponseFrame\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..sharing.nearby.ConnectionResponseFrame.StatusR\x06status\x12m\n" +
	"\x12attachment_details\x18\x02 \x03(\v2>.sharing.nearby.ConnectionResponseFrame.AttachmentDetailsEntryR\x11attachmentDetails\x12G\n" +
	"\x0fstream_metadata\x18\x03 \x03(\v2\x1e.sharing.nearby.StreamMetadataR\x0estreamMetadata\x1ag\n" +
	"\x16AttachmentDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.sharing.nearby.AttachmentDetailsR\x05value:\x028\x01\"s\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x01\x12\n" +
	"\n" +
	"\x06REJECT\x10\x02\x12\x14\n" +
	"\x10NOT_ENOUGH_SPACE\x10\x03\x12\x1f\n" +
	"\x1bUNSUPPORTED_ATTACHMENT_TYPE\x10\x04\x12\r\n" +
	"\tTIMED_OUT\x10\x05\"\x82\x02\n" +
	"\x11AttachmentDetails\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.sharing.nearby.AttachmentDetails.TypeR\x04type\x12]\n" +
	"\x17file_attachment_details\x18\x02 \x01(\v2%.sharing.nearby.FileAttachmentDetailsR\x15fileAttachmentDetails\"R\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04FILE\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\x14\n" +
	"\x10WIFI_CREDENTIALS\x10\x03\x12\a\n" +
	"\x03APP\x10\x04\x12\n" +
	"\n" +
	"\x06STREAM\x10\x05\"\xbf\x02\n" +
	"\x15FileAttachmentDetails\x12=\n" +
	"\x1breceiver_existing_file_size\x18\x01 \x01(\x03R\x18receiverExistingFileSize\x12{\n" +
	"\x18attachment_hash_payloads\x18\x02 \x03(\v2A.sharing.nearby.FileAttachmentDetails.AttachmentHashPayloadsEntryR\x16attachmentHashPayloads\x1aj\n" +
	"\x1bAttachmentHashPayloadsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.sharing.nearby.PayloadsDetailsR\x05value:\x028\x01\"Z\n" +
	"\x0fPayloadsDetails\x12G\n" +
	"\x0fpayload_details\x18\x01 \x03(\v2\x1e.sharing.nearby.PayloadDetailsR\x0epayloadDetails\"p\n" +
	"\x0ePayloadDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12:\n" +
	"\x19creation_timestamp_millis\x18\x02 \x01(\x03R\x17creationTimestampMillis\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xc8\x01\n" +
	"\x18PairedKeyEncryptionFrame\x12\x1f\n" +
	"\vsigned_data\x18\x01 \x01(\fR\n" +
	"signedData\x12$\n" +
	"\x0esecret_id_hash\x18\x02 \x01(\fR\fsecretIdHash\x120\n" +
	"\x14optional_signed_data\x18\x03 \x01(\fR\x12optionalSignedData\x123\n" +
	"\x16qr_code_handshake_data\x18\x04 \x01(\fR\x13qrCodeHandshakeData\"\xd5\x01\n" +
	"\x14PairedKeyResultFrame\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.sharing.nearby.PairedKeyResultFrame.StatusR\x06status\x12>\n" +
	"\aos_type\x18\x02 \x01(\x0e2%.location.nearby.proto.sharing.OSTypeR\x06osType\"8\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02\x12\n" +
	"\n" +
	"\x06UNABLE\x10\x03\"h\n" +
	"\x14CertificateInfoFrame\x12P\n" +
	"\x12public_certificate\x18\x01 \x03(\v2!.sharing.nearby.PublicCertificateR\x11publicCertificate\"\xad\x02\n" +
	"\x11PublicCertificate\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\fR\bsecretId\x12)\n" +
	"\x10authenticity_key\x18\x02 \x01(\fR\x0fauthenticityKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x128\n" +
	"\x18encrypted_metadata_bytes\x18\x06 \x01(\fR\x16encryptedMetadataBytes\x12=\n" +
	"\x1bmetadata_encryption_key_tag\x18\a \x01(\fR\x18metadataEncryptionKeyTag\"U\n" +
	"\x0fWifiCredentials\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12&\n" +
	"\vhidden_ssid\x18\x02 \x01(\b:\x05falseR\n" +
	"hiddenSsid\"h\n" +
	"\rStreamDetails\x12W\n" +
	")input_stream_parcel_file_descriptor_bytes\x18\x01 \x01(\fR$inputStreamParcelFileDescriptorBytesB;\n" +
	"%com.google.android.gms.nearby.sharingB\bProtocolH\x03\xa2\x02\x05GNSHP"

var (
	file_wire_format_proto_rawDescOnce sync.Once
	file_wire_format_proto_rawDescData []byte
)

func file_wire_format_proto_rawDescGZIP() []byte {
	file_wire_format_proto_rawDescOnce.Do(func() {
		file_wire_format_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_format_proto_rawDesc), len(file_wire_format_proto_rawDesc)))
	})
	return file_wire_format_proto_rawDescData
}

var file_wire_format_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_wire_format_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_wire_format_proto_goTypes = []any{
	(FileMetadata_Type)(0),                    // 0: sharing.nearby.FileMetadata.Type
	(TextMetadata_Type)(0),                    // 1: sharing.nearby.TextMetadata.Type
	(WifiCredentialsMetadata_SecurityType)(0), // 2: sharing.nearby.WifiCredentialsMetadata.SecurityType
	(Frame_Version)(0),                        // 3: sharing.nearby.Frame.Version
	(V1Frame_FrameType)(0),                    // 4: sharing.nearby.V1Frame.FrameType
	(IntroductionFrame_SharingUseCase)(0),     // 5: sharing.nearby.IntroductionFrame.SharingUseCase
	(ConnectionResponseFrame_Status)(0),       // 6: sharing.nearby.ConnectionResponseFrame.Status
	(AttachmentDetails_Type)(0),               // 7: sharing.nearby.AttachmentDetails.Type
	(PairedKeyResultFrame_Status)(0),          // 8: sharing.nearby.PairedKeyResultFrame.Status
	(*FileMetadata)(nil),                      // 9: sharing.nearby.FileMetadata
	(*TextMetadata)(nil),                      // 10: sharing.nearby.TextMetadata
	(*WifiCredentialsMetadata)(nil),           // 11: sharing.nearby.WifiCredentialsMetadata
	(*AppMetadata)(nil),                       // 12: sharing.nearby.AppMetadata
	(*StreamMetadata)(nil),                    // 13: sharing.nearby.StreamMetadata
	(*Frame)(nil),                             // 14: sharing.nearby.Frame
	(*V1Frame)(nil),                           // 15: sharing.nearby.V1Frame
	(*IntroductionFrame)(nil),                 // 16: sharing.nearby.IntroductionFrame
	(*ProgressUpdateFrame)(nil),               // 17: sharing.nearby.ProgressUpdateFrame
	(*ConnectionResponseFrame)(nil),           // 18: sharing.nearby.ConnectionResponseFrame
	(*AttachmentDetails)(nil),                 // 19: sharing.nearby.AttachmentDetails
	(*FileAttachmentDetails)(nil),             // 20: sharing.nearby.FileAttachmentDetails
	(*PayloadsDetails)(nil),                   // 21: sharing.nearby.PayloadsDetails
	(*PayloadDetails)(nil),                    // 22: sharing.nearby.PayloadDetails
	(*PairedKeyEncryptionFrame)(nil),          // 23: sharing.nearby.PairedKeyEncryptionFrame
	(*PairedKeyResultFrame)(nil),              // 24: sharing.nearby.PairedKeyResultFrame
	(*CertificateInfoFrame)(nil),              // 25: sharing.nearby.CertificateInfoFrame
	(*PublicCertificate)(nil),                 // 26: sharing.nearby.PublicCertificate
	(*WifiCredentials)(nil),                   // 27: sharing.nearby.WifiCredentials
	(*StreamDetails)(nil),                     // 28: sharing.nearby.StreamDetails
	nil,                                       // 29: sharing.nearby.ConnectionResponseFrame.AttachmentDetailsEntry
	nil,                                       // 30: sharing.nearby.FileAttachmentDetails.AttachmentHashPayloadsEntry
	(sharingenums.OSType)(0),                  // 31: location.nearby.proto.sharing.OSType
}
var file_wire_format_proto_depIdxs = []int32{
	0,  // 0: sharing.nearby.FileMetadata.type:type_name -> sharing.nearby.FileMetadata.Type
	1,  // 1: sharing.nearby.TextMetadata.type:type_name -> sharing.nearby.TextMetadata.Type
	2,  // 2: sharing.nearby.WifiCredentialsMetadata.security_type:type_name -> sharing.nearby.WifiCredentialsMetadata.SecurityType
	3,  // 3: sharing.nearby.Frame.version:type_name -> sharing.nearby.Frame.Version
	15, // 4: sharing.nearby.Frame.v1:type_name -> sharing.nearby.V1Frame
	4,  // 5: sharing.nearby.V1Frame.type:type_name -> sharing.nearby.V1Frame.FrameType
	16, // 6: sharing.nearby.V1Frame.introduction:type_name -> sharing.nearby.IntroductionFrame
	18, // 7: sharing.nearby.V1Frame.connection_response:type_name -> sharing.nearby.ConnectionResponseFrame
	23, // 8: sharing.nearby.V1Frame.paired_key_encryption:type_name -> sharing.nearby.PairedKeyEncryptionFrame
	24, // 9: sharing.nearby.V1Frame.paired_key_result:type_name -> sharing.nearby.PairedKeyResultFrame
	25, // 10: sharing.nearby.V1Frame.certificate_info:type_name -> sharing.nearby.CertificateInfoFrame
	17, // 11: sharing.nearby.V1Frame.progress_update:type_name -> sharing.nearby.ProgressUpdateFrame
	9,  // 12: sharing.nearby.IntroductionFrame.file_metadata:type_name -> sharing.nearby.FileMetadata
	10, // 13: sharing.nearby.IntroductionFrame.text_metadata:type_name -> sharing.nearby.TextMetadata
	11, // 14: sharing.nearby.IntroductionFrame.wifi_credentials_metadata:type_name -> sharing.nearby.WifiCredentialsMetadata
	12, // 15: sharing.nearby.IntroductionFrame.app_metadata:type_name -> sharing.nearby.AppMetadata
	13, // 16: sharing.nearby.IntroductionFrame.stream_metadata:type_name -> sharing.nearby.StreamMetadata
	5,  // 17: sharing.nearby.IntroductionFrame.use_case:type_name -> sharing.nearby.IntroductionFrame.SharingUseCase
	6,  // 18: sharing.nearby.ConnectionResponseFrame.status:type_name -> sharing.nearby.ConnectionResponseFrame.Status
	29, // 19: sharing.nearby.ConnectionResponseFrame.attachment_details:type_name -> sharing.nearby.ConnectionResponseFrame.AttachmentDetailsEntry
	13, // 20: sharing.nearby.ConnectionResponseFrame.stream_metadata:type_name -> sharing.nearby.StreamMetadata
	7,  // 21: sharing.nearby.AttachmentDetails.type:type_name -> sharing.nearby.AttachmentDetails.Type
	20, // 22: sharing.nearby.AttachmentDetails.file_attachment_details:type_name -> sharing.nearby.FileAttachmentDetails
	30, // 23: sharing.nearby.FileAttachmentDetails.attachment_hash_payloads:type_name -> sharing.nearby.FileAttachmentDetails.AttachmentHashPayloadsEntry
	22, // 24: sharing.nearby.PayloadsDetails.payload_details:type_name -> sharing.nearby.PayloadDetails
	8,  // 25: sharing.nearby.PairedKeyResultFrame.status:type_name -> sharing.nearby.PairedKeyResultFrame.Status
	31, // 26: sharing.nearby.PairedKeyResultFrame.os_type:type_name -> location.nearby.proto.sharing.OSType
	26, // 27: sharing.nearby.CertificateInfoFrame.public_certificate:type_name -> sharing.nearby.PublicCertificate
	19, // 28: sharing.nearby.ConnectionResponseFrame.AttachmentDetailsEntry.value:type_name -> sharing.nearby.AttachmentDetails
	21, // 29: sharing.nearby.FileAttachmentDetails.AttachmentHashPayloadsEntry.value:type_name -> sharing.nearby.PayloadsDetails
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_wire_format_proto_init() }
func file_wire_format_proto_init() {
	if File_wire_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_format_proto_rawDesc), len(file_wire_format_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_format_proto_goTypes,
		DependencyIndexes: file_wire_format_proto_depIdxs,
		EnumInfos:         file_wire_format_proto_enumTypes,
		MessageInfos:      file_wire_format_proto_msgTypes,
	}.Build()
	File_wire_format_proto = out.File
	file_wire_format_proto_goTypes = nil
	file_wire_format_proto_depIdxs = nil
}
