# busybox udhcpd for the Kindle SoftAP.
start           192.168.55.10
end             192.168.55.50
interface       wlan0
max_leases      8

opt     subnet  255.255.255.0
opt     router  192.168.55.1
opt     dns     192.168.55.1
opt     lease   600

pidfile         /tmp/udhcpd.pid
lease_file      /tmp/udhcpd.leases
